import Foundation
@testable import WALICatalogRuntime
import XCTest

final class CatalogProductionConfigurationTests: XCTestCase {
    private let directID = "io.github.codewithinferno.wali.WALI"

    private var values: [String: String] {
        let key = "sb_publishable_" + String(repeating: "x", count: 32)
        return [
            "WALI_MARKETPLACE_ENABLED": "YES", "WALI_RELEASE_MODE": "production",
            "WALI_AUTHENTICATION_METHOD": "email_otp", "WALI_SUPABASE_PROJECT_REF": "afgxvhhubqzgpijcstsv",
            "WALI_SUPABASE_URL": "https://afgxvhhubqzgpijcstsv.supabase.co",
            "WALI_SUPABASE_PUBLISHABLE_KEY": key,
            "WALI_SUPABASE_PUBLISHABLE_KEY_SHA256": CatalogProductionConfiguration.sha256(Data(key.utf8)),
            "WALI_CATALOG_CDN_HOST": "afgxvhhubqzgpijcstsv.supabase.co",
            "WALI_CATALOG_SIGNING_KEY_ID": "fixture-primary",
            "WALI_CATALOG_SIGNING_PUBLIC_KEY_BASE64": Data(repeating: 97, count: 32).base64EncodedString(),
            "WALI_CATALOG_RECOVERY_SIGNING_KEY_ID": "fixture-recovery",
            "WALI_CATALOG_RECOVERY_SIGNING_PUBLIC_KEY_BASE64": Data(repeating: 98, count: 32).base64EncodedString(),
            "WALI_LEGAL_BASE_URL": "https://github.com/CodeWithInferno/WALI/blob/main/docs/legal",
        ]
    }

    private var info: [String: Any] {
        var result: [String: Any] = [:]
        for (key, field) in CatalogProductionConfiguration.fields { result[field] = values[key] }
        result["WALIProductionConfigurationSHA256"] = CatalogProductionConfiguration.digest(values: values)
        return result
    }

    func testProductionEmailConfigurationAndCrossLanguageDigest() throws {
        let environment = try CatalogEnvironment.from(infoDictionary: info, bundleIdentifier: directID)
        XCTAssertEqual(environment.authenticationMethod, .emailOTP)
        XCTAssertEqual(environment.supabaseURL.absoluteString, "https://afgxvhhubqzgpijcstsv.supabase.co")
        // Generated by the independent Ruby production validator fixture.
        XCTAssertEqual(CatalogProductionConfiguration.digest(values: values), "538f9bfe1aba4aa7587b2a38086d7a43e88b0c30a0b955ebf3c10205d1e611e5")
    }

    func testDirectAuthNeverFallsBackOrAcceptsIncompleteOrStagingConfiguration() {
        let mutations: [String: Any] = [
            "WALIAuthenticationMethod": "native_apple", "WALIReleaseMode": "local_preview",
            "WALISupabaseProjectRef": "nkwzjuzoyuanjimexulz",
            "WALIMarketplaceURL": "https://nkwzjuzoyuanjimexulz.supabase.co",
            "WALIApprovedCDNHosts": "other.supabase.co",
            "WALIMarketplacePublishableKey": "sb_secret_private",
            "WALICatalogSigningKeyID": "other", "WALIProductionConfigurationSHA256": String(repeating: "0", count: 64),
        ]
        for (key, value) in mutations {
            var changed = info
            changed[key] = value
            XCTAssertThrowsError(try CatalogEnvironment.from(infoDictionary: changed, bundleIdentifier: directID), key)
        }
        for field in CatalogProductionConfiguration.fields.values {
            var changed = info
            changed.removeValue(forKey: field)
            XCTAssertThrowsError(try CatalogEnvironment.from(infoDictionary: changed, bundleIdentifier: directID), field)
        }
        for method in ["", "disabled", "unknown", "$(WALI_AUTHENTICATION_METHOD)"] {
            var changed = info
            changed["WALIAuthenticationMethod"] = method
            XCTAssertThrowsError(try CatalogEnvironment.from(infoDictionary: changed, bundleIdentifier: directID))
        }
    }

    func testStoreAndDevelopmentKeepNativeAppleAndRejectDirectEmailMode() throws {
        for identifier in ["com.wali.store.WALI", "com.wali.store.development.WALI", "com.wali.development.WALI", "com.wali.debug.WALI"] {
            XCTAssertThrowsError(try CatalogEnvironment.from(infoDictionary: info, bundleIdentifier: identifier))
            var native = info
            native["WALIAuthenticationMethod"] = "native_apple"
            XCTAssertEqual(try CatalogEnvironment.from(infoDictionary: native, bundleIdentifier: identifier).authenticationMethod, .nativeApple)
        }
    }

    func testDisabledMarketplaceNeverConstructsAuthEnvironment() {
        var disabled = info
        disabled["WALIMarketplaceEnabled"] = "NO"
        XCTAssertThrowsError(try CatalogEnvironment.from(infoDictionary: disabled, bundleIdentifier: directID))
    }
}
