import Foundation
import WALIModel

/// Stable identity for one immutable worker attempt.
public struct MediaAttemptID: Codable, Sendable, Hashable {
    public let jobID: JobID
    public let generation: AttemptGeneration

    public init(jobID: JobID, generation: AttemptGeneration) {
        self.jobID = jobID
        self.generation = generation
    }
}

/// Exact artifact families produced by the private preparation pipeline.
public enum MediaArtifactKind: String, Codable, Sendable, Hashable, CaseIterable {
    case masterVideo = "master_video"
    case previewVideo = "preview_video"
    case posterImage = "poster_image"
    case masterImage = "master_image"

    public static func required(for kind: WallpaperMediaKind) -> Set<Self> {
        kind == .video ? [.masterVideo, .previewVideo, .posterImage] : [.masterImage, .posterImage]
    }
}

/// A bounded, immutable media conversion request.
public struct MediaTranscodeRequest: Codable, Sendable, Hashable {
    public static let maximumSourceByteCount: UInt64 = 20 * 1_024 * 1_024 * 1_024
    public static let maximumStillSourceByteCount: UInt64 = 128 * 1_024 * 1_024

    public let attempt: MediaAttemptID
    public let sourceURL: URL
    public let stagingDirectoryURL: URL
    public let sourceByteLimit: UInt64
    public let mediaKind: WallpaperMediaKind

    public init(
        attempt: MediaAttemptID,
        sourceURL: URL,
        stagingDirectoryURL: URL,
        sourceByteLimit: UInt64? = nil,
        mediaKind: WallpaperMediaKind = .video
    ) throws {
        guard sourceURL.isFileURL, stagingDirectoryURL.isFileURL else {
            throw MediaPipelineError.invalidFileURL
        }
        let maximum = mediaKind == .still ? Self.maximumStillSourceByteCount : Self.maximumSourceByteCount
        let limit = sourceByteLimit ?? maximum
        guard limit > 0, limit <= maximum else {
            throw MediaPipelineError.sourceTooLarge(limit: maximum)
        }
        self.attempt = attempt
        self.sourceURL = sourceURL
        self.stagingDirectoryURL = stagingDirectoryURL
        self.sourceByteLimit = limit
        self.mediaKind = mediaKind
    }
}

/// True raster facts; no duration or frame-rate stand-ins are present.
public struct StillMediaInspection: Codable, Sendable, Hashable {
    public let byteCount: UInt64
    public let pixelSize: PixelSize
    public let frameCount: UInt32
    public let bitsPerComponent: UInt16
    public let colorSpace: String
    public let hasAlpha: Bool

    public init(byteCount: UInt64, pixelSize: PixelSize, frameCount: UInt32 = 1,
                bitsPerComponent: UInt16, colorSpace: String, hasAlpha: Bool) {
        self.byteCount = byteCount
        self.pixelSize = pixelSize
        self.frameCount = frameCount
        self.bitsPerComponent = bitsPerComponent
        self.colorSpace = colorSpace
        self.hasAlpha = hasAlpha
    }
}

public enum MediaInspectionContent: Codable, Sendable, Hashable {
    case video(MediaInspection)
    case still(StillMediaInspection)

    public var mediaKind: WallpaperMediaKind {
        switch self { case .video: .video; case .still: .still }
    }
}

/// Media facts derived from source or generated bytes.
public struct MediaInspection: Codable, Sendable, Hashable {
    public let byteCount: UInt64
    public let pixelSize: PixelSize
    public let durationSeconds: Double
    public let nominalFrameRate: Double
    public let hasAudio: Bool
    public let isHDR: Bool
    public let videoCodec: String
    public let bitDepth: UInt16?
    public let hevcProfileIDC: UInt8?

    public init(
        byteCount: UInt64,
        pixelSize: PixelSize,
        durationSeconds: Double,
        nominalFrameRate: Double,
        hasAudio: Bool,
        isHDR: Bool,
        videoCodec: String,
        bitDepth: UInt16? = nil,
        hevcProfileIDC: UInt8? = nil
    ) {
        self.byteCount = byteCount
        self.pixelSize = pixelSize
        self.durationSeconds = durationSeconds
        self.nominalFrameRate = nominalFrameRate
        self.hasAudio = hasAudio
        self.isHDR = isHDR
        self.videoCodec = videoCodec
        self.bitDepth = bitDepth
        self.hevcProfileIDC = hevcProfileIDC
    }
}

/// An untrusted worker claim. The agent must re-hash and re-inspect the bytes.
public struct MediaArtifactClaim: Codable, Sendable, Hashable {
    public let kind: MediaArtifactKind
    public let stagedURL: URL
    public let digest: ContentDigest
    public let byteCount: UInt64
    public let inspection: MediaInspectionContent?

    public var videoInspection: MediaInspection? {
        guard case .video(let value) = inspection else { return nil }
        return value
    }

    public init(
        kind: MediaArtifactKind,
        stagedURL: URL,
        digest: ContentDigest,
        byteCount: UInt64,
        inspection: MediaInspection?
    ) {
        self.kind = kind
        self.stagedURL = stagedURL
        self.digest = digest
        self.byteCount = byteCount
        self.inspection = inspection.map(MediaInspectionContent.video)
    }

    public init(kind: MediaArtifactKind, stagedURL: URL, digest: ContentDigest,
                byteCount: UInt64, inspection: MediaInspectionContent) {
        self.kind = kind
        self.stagedURL = stagedURL
        self.digest = digest
        self.byteCount = byteCount
        self.inspection = inspection
    }
}

/// Complete output for one worker attempt.
public struct MediaTranscodeResult: Codable, Sendable, Hashable {
    public let attempt: MediaAttemptID
    public let suggestedDisplayName: String
    public let completedAt: Date
    public let sourceDigest: ContentDigest
    public let sourceInspection: MediaInspectionContent
    public let claims: [MediaArtifactClaim]

    public init(
        attempt: MediaAttemptID,
        suggestedDisplayName: String,
        completedAt: Date = Date(),
        sourceDigest: ContentDigest,
        sourceInspection: MediaInspection,
        claims: [MediaArtifactClaim]
    ) throws {
        try self.init(attempt: attempt, suggestedDisplayName: suggestedDisplayName,
            completedAt: completedAt, sourceDigest: sourceDigest,
            sourceInspection: .video(sourceInspection), claims: claims)
    }

    public init(attempt: MediaAttemptID, suggestedDisplayName: String,
                completedAt: Date = Date(), sourceDigest: ContentDigest,
                sourceInspection: MediaInspectionContent, claims: [MediaArtifactClaim]) throws {
        let required = MediaArtifactKind.required(for: sourceInspection.mediaKind)
        guard claims.count == required.count,
              Set(claims.map(\.kind)) == required,
              claims.allSatisfy({ claim in
                  if sourceInspection.mediaKind == .video && claim.kind == .posterImage {
                      return claim.inspection == nil
                  }
                  return claim.inspection?.mediaKind == sourceInspection.mediaKind
              })
        else {
            throw MediaPipelineError.incompleteOutput
        }
        self.attempt = attempt
        self.suggestedDisplayName = suggestedDisplayName
        self.completedAt = completedAt
        self.sourceDigest = sourceDigest
        self.sourceInspection = sourceInspection
        self.claims = claims.sorted { $0.kind.rawValue < $1.kind.rawValue }
    }
}

public enum MediaPipelineError: Error, Sendable, Equatable {
    case invalidFileURL
    case sourceMissing
    case sourceNotRegular
    case sourceIsSymbolicLink
    case sourceTooLarge(limit: UInt64)
    case unreadableAsset
    case missingVideoTrack
    case invalidDuration
    case unsupportedDimensions
    case unsupportedFrameRate
    case cannotCreateStagingDirectory
    case cannotCreateExporter
    case unsupportedHEVCExport
    case exportFailed(String)
    case posterGenerationFailed(String)
    case outputVerificationFailed(MediaArtifactKind)
    case incompleteOutput
    case unsupportedStillImage
    case insufficientStorage(requiredBytes: UInt64, availableBytes: UInt64)
}

extension MediaPipelineError: LocalizedError {
    public var errorDescription: String? {
        switch self {
        case .invalidFileURL: "Media paths must be local file URLs."
        case .sourceMissing: "The selected source file no longer exists."
        case .sourceNotRegular: "The selected source is not a regular file."
        case .sourceIsSymbolicLink: "Symbolic-link sources are not accepted."
        case let .sourceTooLarge(limit): "The source exceeds the \(limit)-byte import limit."
        case .unreadableAsset: "The media file cannot be read by AVFoundation."
        case .missingVideoTrack: "The media file must contain exactly one video track."
        case .invalidDuration: "The media duration is empty or unsupported."
        case .unsupportedDimensions: "The media dimensions are empty or exceed WALI's limits."
        case .unsupportedFrameRate: "The media frame rate exceeds WALI's limit."
        case .cannotCreateStagingDirectory: "WALI could not create private staging storage."
        case .cannotCreateExporter: "AVFoundation could not create a media exporter."
        case .unsupportedHEVCExport: "This Mac cannot export the requested HEVC profile."
        case let .exportFailed(message): "Media export failed: \(message)"
        case let .posterGenerationFailed(message): "Poster generation failed: \(message)"
        case let .outputVerificationFailed(kind): "Generated \(kind.rawValue) verification failed."
        case .incompleteOutput: "The conversion did not produce every required artifact."
        case .unsupportedStillImage: "Use a single-frame, 8-bit sRGB JPEG or PNG within the image size limits. Export without an embedded ICC profile."
        case let .insufficientStorage(requiredBytes, availableBytes):
            "This import needs about \(requiredBytes.formatted(.byteCount(style: .file))) free, but only \(availableBytes.formatted(.byteCount(style: .file))) is available."
        }
    }
}
