#!/usr/bin/env python3
"""Bundle exact versioned legal documents for the public read-only Edge endpoint."""
import argparse
import hashlib
import json
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCUMENTS = {"creator-content-license": "2026-09-12", "wallpaper-use-license": "2026-09-12"}

def generated():
    values = {}
    for slug, version in DOCUMENTS.items():
        body = (ROOT / "docs/legal" / (slug + ".md")).read_text()
        values[slug + "/" + version] = {"body": body, "sha256": hashlib.sha256(body.encode()).hexdigest()}
    raw = "// Generated by scripts/generate-catalog-legal.py; edit the versioned source documents.\nexport const catalogLegalDocuments: Readonly<Record<string, {body: string; sha256: string}>> = " + json.dumps(values, indent=2, ensure_ascii=False) + ";\n"
    return subprocess.run(["deno", "fmt", "--ext", "ts", "-"], input=raw, text=True, capture_output=True, check=True).stdout

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    output = ROOT / "supabase/functions/catalog-legal/documents.generated.ts"
    expected = generated()
    if args.check:
        if not output.exists() or output.read_text() != expected:
            raise SystemExit("Versioned legal bundle differs from its source; regenerate explicitly.")
    else:
        output.write_text(expected)
