[storage]
driver = "overlay"
runroot = "/run/wali-media-worker/containers"
graphroot = "/var/lib/wali-worker/containers"
volume_path = "/var/lib/wali-worker/volumes"

[storage.options.overlay]
mount_program = "/usr/bin/fuse-overlayfs"
